Repository FutureNHS/futurenhs-platform, pull requests merged in 2020-10, with the labels that each got.

#300 delete hello-world service
  .github/dependabot.yml
  .github/workflows/hello-world-branch.yaml
  .github/workflows/hello-world-master.yaml
  .github/workflows/linting.yaml
  frontend/README.md
  frontend/package.json
  frontend/server.js
  frontend/yarn.lock
  hello-world/.dockerignore
  hello-world/Cargo.lock
  hello-world/Cargo.toml
  hello-world/Dockerfile
  hello-world/LICENSE
  hello-world/Makefile
  hello-world/README.md
  hello-world/manifests/base/deployment.yaml
  hello-world/manifests/base/kustomization.yaml
  hello-world/manifests/base/service.yaml
  hello-world/manifests/dev-template/deployment.yaml
  hello-world/manifests/dev-template/favourite-cuisine-sealed.yaml
  hello-world/manifests/dev-template/kustomization.yaml
  hello-world/manifests/production/deployment.yaml
  hello-world/manifests/production/favourite-cuisine-sealed.yaml
  hello-world/manifests/production/kustomization.yaml
  hello-world/src/lib.rs
  hello-world/src/main.rs
  hello-world/tests/hello_world.rs
  infrastructure/kubernetes/argocd/apps/dev-template/hello-world.yaml
  infrastructure/kubernetes/argocd/apps/dev-template/kustomization.yaml
  infrastructure/kubernetes/argocd/apps/production/hello-world.yaml
  infrastructure/kubernetes/argocd/apps/production/kustomization.yaml
  infrastructure/modules/databases/main.tf
  infrastructure/scripts/create-dev-overlays.py
  test/README.md
Labels: great gif :framed_picture:

#323 Improve nav-header test
  test/internet-explorer/nav-header.js
Labels: ready for review 🎉

#344 1817 create user table and user mutations
  workspace-service/graphql-schema.json
  workspace-service/migrations/20201009093453_create_user_table.sql
  workspace-service/sql/users/get_or_create.sql
  workspace-service/sql/users/update.sql
  workspace-service/sqlx-data.json
  workspace-service/src/db.rs
  workspace-service/src/graphql/mod.rs
  workspace-service/src/graphql/users.rs
Labels: wip :construction:

#366 Setup script fixes
  workspace-service/Makefile
  workspace-service/migrations/20201014134400_create_admin_user.sql
  workspace-service/scripts/create-default-test-folders.sh
  workspace-service/scripts/create-file-if-needed.sh
  workspace-service/scripts/create-workspace-if-needed.sh
Labels: great gif :framed_picture:

#391 Ab1800 filename validation
  workspace-service/.gitignore
  workspace-service/Cargo.lock
  workspace-service/Cargo.toml
  workspace-service/src/db.rs
  workspace-service/src/graphql/files.rs
  workspace-service/src/graphql/workspaces.rs
Labels: ready for review 🎉

#396 Better errors
  workspace-service/src/graphql/files.rs
  workspace-service/src/graphql/mod.rs
  workspace-service/src/graphql/validation.rs
Labels: ready for review 🎉

#397 Design sweep
  frontend/__tests__/pages/admin/__snapshots__/create-workspace.test.tsx.snap
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/__snapshots__/index.test.tsx.snap
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/__snapshots__/upload-file.test.tsx.snap
  frontend/__tests__/pages/workspaces/__snapshots__/[workspaceId].test.tsx.snap
  frontend/__tests__/pages/workspaces/__snapshots__/directory.test.tsx.snap
  frontend/components/FileTable/FileTable.tsx
  frontend/components/FileTable/MobileFileList.tsx
  frontend/components/H2/H2.tsx
  frontend/components/H2/index.tsx
  frontend/components/MainHeading/MainHeading.test.tsx
  frontend/components/MainHeading/MainHeading.tsx
  frontend/components/MainHeading/__snapshots__/MainHeading.test.tsx.snap
  frontend/components/Menu/Menu.tsx
  frontend/components/Menu/MenuButton.tsx
  frontend/components/Menu/__snapshots__/Menu.test.tsx.snap
  frontend/components/NavListItem/NavListItem.tsx
  frontend/components/NavListItem/__snapshots__/NavListItem.test.tsx.snap
  frontend/components/NavSection/NavSection.tsx
  frontend/components/NavSection/__snapshots__/NavSection.test.tsx.snap
  frontend/components/Navigation/Navigation.tsx
  frontend/components/Navigation/__snapshots__/Navigation.test.tsx.snap
  frontend/components/Workspaces/WorkspaceDirectoryItem.tsx
  frontend/components/Workspaces/__snapshots__/WorkspaceDirectoryItem.test.tsx.snap
  frontend/cypress/integration/frontend/workspaces/directory.js
  frontend/cypress/integration/frontend/workspaces/folders/browse-files.js
  frontend/cypress/integration/frontend/workspaces/folders/upload-files.js
  frontend/pages/admin/create-workspace.tsx
  frontend/pages/workspaces/[workspaceId].tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId].tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/upload-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/create-folder.tsx
  frontend/pages/workspaces/directory.tsx
  frontend/public/chevronClosed.svg
  frontend/public/chevronOpen.svg
Labels: ready for test :mag:

#401 Upload form for file version
  frontend/.eslintrc.json
  frontend/codegen.yaml
  frontend/containers/UploadFileForm/CreateFileForm.tsx
  frontend/containers/UploadFileForm/UpdateFileForm.tsx
  frontend/containers/UploadFileForm/createFileVersion.graphql
  frontend/containers/UploadFileForm/index.tsx
  frontend/containers/UploadFileForm/styles.tsx
  frontend/cypress/integration/frontend/admin/create-workspace.js
  frontend/lib/uploadBlob.ts
  frontend/lib/useMaxLengthHelper.ts
  frontend/lib/withUrqlClient.ts
  frontend/pages/admin/create-workspace.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/upload-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/create-folder.tsx
Labels: ready for test :mag:

#422 remove snapshot tests of pages/*
  frontend/__tests__/pages/admin/__snapshots__/create-workspace.test.tsx.snap
  frontend/__tests__/pages/admin/create-workspace.test.tsx
  frontend/__tests__/pages/workspaces/[workspaceId]/__snapshots__/index.test.tsx.snap
  frontend/__tests__/pages/workspaces/[workspaceId]/__snapshots__/members.test.tsx.snap
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/__snapshots__/index.test.tsx.snap
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/__snapshots__/upload-file.test.tsx.snap
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/index.test.tsx
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/upload-file.test.tsx
  frontend/__tests__/pages/workspaces/[workspaceId]/index.test.tsx
  frontend/__tests__/pages/workspaces/[workspaceId]/members.test.tsx
  frontend/__tests__/pages/workspaces/__snapshots__/directory.test.tsx.snap
  frontend/__tests__/pages/workspaces/directory.test.tsx
Labels: great gif :framed_picture:

#400 Group tables migration
  workspace-service/migrations/20201022135333_groups.sql
  workspace-service/sql/groups/create.sql
  workspace-service/sql/workspaces/create.sql
  workspace-service/sql/workspaces/delete.sql
  workspace-service/sql/workspaces/find_all.sql
  workspace-service/sql/workspaces/find_by_id.sql
  workspace-service/sql/workspaces/update.sql
  workspace-service/sqlx-data.json
  workspace-service/src/db/groups.rs
  workspace-service/src/db/mod.rs
  workspace-service/src/db/workspaces.rs
Labels: qa approved :shipit:

#416 "Update file" page
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/update-file.test.tsx
  frontend/components/FileTable/MobileFileList.tsx
  frontend/components/MainHeading/MainHeading.tsx
  frontend/components/MainHeading/__snapshots__/MainHeading.test.tsx.snap
  frontend/components/Menu/MenuList.tsx
  frontend/components/Menu/MenuListItem.tsx
  frontend/containers/UploadFileForm/CreateFileForm.tsx
  frontend/containers/UploadFileForm/UpdateFileForm.tsx
  frontend/containers/UploadFileForm/createFileVersion.graphql
  frontend/containers/UploadFileForm/styles.tsx
  frontend/cypress/fixtures/file-graphql-response.json
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/update-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/files.graphql
Labels: ready for test :mag:

#418 Ab2072 workspace members 2
  frontend/components/MainHeading/MainHeading.tsx
  frontend/pages/workspaces/[workspaceId]/members.tsx
Labels: no qa needed, ready for review 🎉

#426 [BUG 2320 / 2321] Copy changes
  frontend/components/Navigation/Navigation.tsx
  frontend/cypress/integration/frontend/workspaces/folders/upload-files.js
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/upload-file.tsx
Labels: ready for review 🎉

#427 [BUG 2322] Fix font size for workspace nav links
  frontend/components/Navigation/Navigation.tsx
  frontend/components/Navigation/__snapshots__/Navigation.test.tsx.snap
Labels: great gif :framed_picture:, ready for review 🎉

#420 FileCreated and FileUpdated events
  event-models/README.md
  event-models/rust/src/models.rs
  event-models/schema.json
  event-models/typescript/src/schema.ts
  workspace-service/src/graphql/files.rs
Labels: ready for review 🎉

#432 Footer
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/update-file.test.tsx
  frontend/components/Footer/Footer.test.tsx
  frontend/components/Footer/Footer.tsx
  frontend/components/Footer/__snapshots__/Footer.test.tsx.snap
  frontend/components/Footer/index.tsx
  frontend/components/Icon/BetaIcon.tsx
  frontend/components/Icon/OGLIcon.tsx
  frontend/components/Icon/index.tsx
  frontend/components/Navigation/Navigation.tsx
  frontend/components/Navigation/__snapshots__/Navigation.test.tsx.snap
  frontend/cypress/integration/frontend/footer.js
  frontend/pages/_app.scss
  frontend/pages/admin/create-workspace.tsx
  frontend/pages/auth-page-layouts/login.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/update-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/upload-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/create-folder.tsx
  frontend/pages/workspaces/[workspaceId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/members.tsx
  frontend/pages/workspaces/directory.tsx
  frontend/yarn.lock
Labels: ready for review 🎉
