Repository FutureNHS/futurenhs-platform, pull requests merged in 2020-11, with the labels that each got.

#449 rename groups to teams in db
  workspace-service/graphql-schema.json
  workspace-service/migrations/20201102110421_rename-group-to-teamteam.sql
  workspace-service/sql/groups/group_members.sql
  workspace-service/sql/teams/create.sql
  workspace-service/sql/teams/members.sql
  workspace-service/sqlx-data.json
  workspace-service/src/db/mod.rs
  workspace-service/src/db/teams.rs
  workspace-service/src/db/workspaces.rs
  workspace-service/src/graphql/workspaces.rs
Labels: no qa needed

#434 Turn file url queries into mutations
  frontend/__tests__/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/__snapshots__/update-file.test.tsx.snap
  frontend/containers/UploadFileForm/CreateFileForm.tsx
  frontend/containers/UploadFileForm/UpdateFileForm.tsx
  frontend/lib/server/graphql.js
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/file-upload.graphql
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/update-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/upload-file.tsx
  frontend/stubServer/resolver.js
  workspace-service/graphql-schema.json
  workspace-service/src/graphql/file_download_urls.rs
  workspace-service/src/graphql/file_upload_urls.rs
  workspace-service/src/graphql/mod.rs
Labels: ready for test :mag:

#424 Generic FileTable
  frontend/components/FileTable/FileTable.test.tsx
  frontend/components/FileTable/FileTable.tsx
  frontend/components/FileTable/MobileFileList.test.tsx
  frontend/components/FileTable/MobileFileList.tsx
  frontend/components/FileTable/index.tsx
  frontend/components/Files/IconCell.tsx
  frontend/components/Files/ModifiedAtCell.tsx
  frontend/components/Files/TitleCell.tsx
  frontend/components/Files/index.ts
  frontend/components/Icon/FileIcon.tsx
  frontend/components/Table/MobileList.test.tsx
  frontend/components/Table/MobileList.tsx
  frontend/components/Table/Table.test.tsx
  frontend/components/Table/Table.tsx
  frontend/components/Table/index.ts
  frontend/cypress/integration/frontend/workspaces/folders/browse-files.js
  frontend/lib/test-helpers/render.tsx
  frontend/lib/test-helpers/urql.ts
  frontend/package.json
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/update-file.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/index.tsx
  frontend/yarn.lock
Labels: qa approved :shipit:

#454 Generate Rust event models with strings
  .github/workflows/event-models-branch.yaml
  event-models/README.md
  event-models/generate-rust.js
  event-models/generate-typescript.js
  event-models/package.json
  event-models/rust/Cargo.toml
  event-models/rust/src/models/generated.rs
  event-models/rust/src/models/mod.rs
  event-models/typescript/package.json
  event-models/typescript/yarn.lock
  event-models/yarn.lock
  workspace-service/Cargo.lock
  workspace-service/src/graphql/files.rs
Labels: no qa needed

#455 [Bug 2259] Change z-index on 'options' Tooltip and MenuList
  frontend/components/Menu/MenuList.tsx
  frontend/components/Menu/__snapshots__/Menu.test.tsx.snap
  frontend/components/Navigation/__snapshots__/Navigation.test.tsx.snap
  frontend/components/Tooltip/Tooltip.tsx
Labels: ready for review 🎉

#458 [Bug 2253] Fix clashing hover/active states on Workspace Directory Items
  frontend/components/Workspaces/WorkspaceDirectoryItem.tsx
  frontend/components/Workspaces/__snapshots__/WorkspaceDirectoryItem.test.tsx.snap
Labels: ready for review 🎉

#450 Add analytics events
  event-models/rust/src/models/generated.rs
  event-models/schema.json
  event-models/typescript/src/schema.ts
  workspace-service/src/graphql/file_download_urls.rs
  workspace-service/src/graphql/files.rs
  workspace-service/src/graphql/folders.rs
  workspace-service/src/graphql/test_mocks.rs
Labels: no qa needed

#457 Bug 2258 - Add hover/focus/active states to Workspace title in folder nav
  frontend/components/Navigation/Navigation.tsx
  frontend/components/Navigation/__snapshots__/Navigation.test.tsx.snap
Labels: ready for review 🎉

#465 Build edit folder page.
  frontend/components/Icon/ChevronBottomIcon.tsx
  frontend/components/Icon/ChevronTopIcon.tsx
  frontend/components/Icon/index.tsx
  frontend/components/Navigation/Navigation.tsx
  frontend/components/Permissions/Permissions.test.tsx
  frontend/components/Permissions/Permissions.tsx
  frontend/components/Permissions/__snapshots__/Permissions.test.tsx.snap
  frontend/components/Permissions/index.tsx
  frontend/components/PermissionsRadio/PermissionsRadio.test.tsx
  frontend/components/PermissionsRadio/PermissionsRadio.tsx
  frontend/components/PermissionsRadio/__snapshots__/PermissionsRadio.test.tsx.snap
  frontend/components/PermissionsRadio/index.tsx
  frontend/package.json
  frontend/pages/_app.scss
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/update-folder.tsx
  frontend/yarn.lock
Labels: ready for review 🎉

#474 [Bug 2255] Add focus/active state to folder nav chevron
  frontend/components/Icon/ChevronBottomIcon.tsx
  frontend/components/Icon/ChevronTopIcon.tsx
  frontend/components/NavSection/NavSection.tsx
  frontend/components/NavSection/__snapshots__/NavSection.test.tsx.snap
  frontend/components/Navigation/__snapshots__/Navigation.test.tsx.snap
  frontend/components/Permissions/Permissions.tsx
  frontend/components/Permissions/__snapshots__/Permissions.test.tsx.snap
Labels: ready for review 🎉

#471 Make changes to create folder, Add workspace service mutations for create and update folder.
  frontend/components/Permissions/Permissions.tsx
  frontend/components/Permissions/__snapshots__/Permissions.test.tsx.snap
  frontend/components/PermissionsRadio/PermissionsRadio.tsx
  frontend/components/PermissionsRadio/__snapshots__/PermissionsRadio.test.tsx.snap
  frontend/cypress/fixtures/create-folder-graphql-response.json
  frontend/cypress/fixtures/folder-graphql-response.json
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/update-folder.tsx
  frontend/pages/workspaces/[workspaceId]/folders/create-folder.tsx
  frontend/pages/workspaces/[workspaceId]/folders/folders.graphql
  workspace-service/graphql-schema.json
  workspace-service/migrations/20201106130906_add_access_to_folders.sql
  workspace-service/sql/folders/create.sql
  workspace-service/sql/folders/delete.sql
  workspace-service/sql/folders/find_by_id.sql
  workspace-service/sql/folders/find_by_workspace.sql
  workspace-service/sql/folders/update.sql
  workspace-service/sqlx-data.json
  workspace-service/src/db/folders.rs
  workspace-service/src/graphql/folders.rs
Labels: ready for review 🎉

#492 Bug 2192 - Fix tabbing order for "Forgot your password" link
  frontend/components/Login/Login.tsx
  frontend/lib/server/requireEnv.js
Labels: ready for review 🎉

#496 Create 'get workspace permissions' query and frontend Error component.
  frontend/components/Error/Error.test.tsx
  frontend/components/Error/Error.tsx
  frontend/components/Error/__snapshots__/Error.test.tsx.snap
  frontend/components/Error/index.tsx
  frontend/lib/withUrqlClient.ts
  frontend/pages/admin/create-workspace.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/update-folder.tsx
  frontend/pages/workspaces/[workspaceId]/members.graphql
  workspace-service/graphql-schema.json
  workspace-service/src/db/workspaces.rs
  workspace-service/src/graphql/folders.rs
  workspace-service/src/graphql/workspaces.rs
Labels: ready for review 🎉

#502 Create sql query for file versions
  workspace-service/sql/file_versions/find_by_file_id.sql
Labels: no qa needed

#500 Trigger events
  event-models/rust/src/models/generated.rs
  event-models/schema.json
  event-models/typescript/src/schema.ts
  frontend/components/Permissions/Permissions.tsx
  frontend/components/Permissions/__snapshots__/Permissions.test.tsx.snap
  frontend/cypress/fixtures/update-folder-graphql-response.json
  frontend/cypress/integration/frontend/workspaces/folders/create-folder.js
  frontend/cypress/integration/frontend/workspaces/folders/update-folder.js
  frontend/stubServer/resolver.js
  workspace-service/src/graphql/folders.rs
Labels: ready for review 🎉

#505 Hide folders from Nav bar when insufficient permissions.
  frontend/lib/withUrqlClient.ts
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/update-folder.tsx
  workspace-service/src/graphql/folders.rs
Labels: ready for review 🎉

#501 File versions mobile view
  frontend/components/EmailLink/EmailLink.test.tsx
  frontend/components/EmailLink/EmailLink.tsx
  frontend/components/EmailLink/__snapshots__/EmailLink.test.tsx.snap
  frontend/components/EmailLink/index.tsx
  frontend/components/Files/ModifiedAtCell.tsx
  frontend/containers/FileInformation/FileInformation.test.tsx
  frontend/containers/FileInformation/FileInformation.tsx
  frontend/containers/FileInformation/__snapshots__/FileInformation.test.tsx.snap
  frontend/containers/FileInformation/index.tsx
  frontend/cypress/fixtures/file-graphql-response.json
  frontend/cypress/fixtures/file-versions-by-file-id-response.json
  frontend/cypress/fixtures/files-by-folder-graphql-response.json
  frontend/cypress/integration/frontend/workspaces/folders/browse-files.js
  frontend/pages/workspaces/[workspaceId]/folders/[folderId]/files/[fileId]/index.tsx
  frontend/pages/workspaces/[workspaceId]/members.tsx
Labels: ready for test :mag:

#509 Add cypress tests for members page.
  frontend/cypress/fixtures/change-workspace-membership-response.json
  frontend/cypress/integration/frontend/workspaces/members.js
  frontend/pages/workspaces/[workspaceId]/members.tsx
  frontend/stubServer/resolver.js
Labels: ready for review 🎉
