Repository FutureNHS/futurenhs-platform, pull requests merged in 2020-06, with the labels that each got.

#10 Add Linkerd setup script
  infrastructure/README.md
  infrastructure/scripts/install-linkerd.sh
Labels: ready for review 🎉

#11 Add Issue and Pull Request Templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review 🎉

#13 Add Test Approach doc
  docs/testing/test_approach.md
  docs/testing/test_pyramid.png
Labels: documentation :file_cabinet:, ready for review 🎉

#12 Hello world
  .github/workflows/hello-world.yml
  .gitignore
  hello-world/.dockerignore
  hello-world/Cargo.lock
  hello-world/Cargo.toml
  hello-world/Dockerfile
  hello-world/LICENSE
  hello-world/Makefile
  hello-world/README.md
  hello-world/dev/deployment.yaml
  hello-world/src/lib.rs
  hello-world/src/main.rs
  hello-world/tests/hello_world.rs
Labels: ready for review 🎉

#15 CI for infrastructure
  .github/workflows/frontend.yml
  .github/workflows/infrastructure.yml
Labels: ready for review 🎉

#14 Adding feature flags and no staging to architectural decision record
  docs/architecture/decisions/0003_feature_flags.md
  docs/architecture/decisions/0004_no_staging_environment.md
  docs/testing/test_approach.md
Labels: documentation :file_cabinet:, ready for review 🎉

#17 Simplify working with infrastructure environments
  docs/ci-setup.md
  infrastructure/README.md
  infrastructure/environments/dev/main.tf
  infrastructure/environments/production/main.tf
  infrastructure/modules/platform/outputs.tf
  infrastructure/modules/platform/variables.tf
  infrastructure/scripts/create-dev-environment.sh
Labels: ready for review 🎉

#19 Fix build trigger for path filters
  .github/workflows/frontend.yml
  .github/workflows/hello-world.yml
  .github/workflows/infrastructure.yml
Labels: ready for review 🎉

#20 Argo CD
  frontend/components/layout.tsx
  infrastructure/README.md
  infrastructure/kubernetes/argocd-setup/applications.yaml
  infrastructure/kubernetes/argocd-setup/install.yaml
  infrastructure/kubernetes/argocd-setup/namespace.yaml
  infrastructure/scripts/install-argo-cd.sh
Labels: ready for review 🎉

#22 High level architecture diagram
  docs/architecture/README.md
  docs/architecture/high-level.drawio
  docs/architecture/high-level.png
Labels: ready for review 🎉

#16 Tracing: Hello world app with `tracing`
  hello-world/Cargo.lock
  hello-world/Cargo.toml
  hello-world/Dockerfile
  hello-world/dev/deployment.yaml
  hello-world/src/lib.rs
  hello-world/src/main.rs
  hello-world/tests/hello_world.rs
  infrastructure/README.md
  infrastructure/environments/dev/outputs.tf
  infrastructure/environments/production/outputs.tf
  infrastructure/kubernetes/logging/container-azm-ms-agentconfig.yaml
  infrastructure/modules/platform/main.tf
  infrastructure/modules/platform/outputs.tf
Labels: great gif :framed_picture:, ready for review 🎉

#30 Document frontend tech choice
  docs/architecture/decisions/0006-frontend-technology.md
Labels: great gif :framed_picture:, ready for review 🎉
